name: Benchmark

on:
  push:
    branches:
      - main

jobs:
  run-benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run benchmark
        run: dotnet run -c Release --project ArrayLoopBench.csproj

      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-artifacts
          path: BenchmarkDotNet.Artifacts

      - name: Create benchmark summary
        run: cat BenchmarkDotNet.Artifacts/results/ArrayLoopBenchmark.Benchmarks-report-github.md >> $GITHUB_STEP_SUMMARY
